env = Environment(
    SCONS_CXX_STANDARD='c++20'
)


env.Append( CPPPATH=['.'])

src_files = [
    Glob('./*.cpp'),
    Glob('./utils/*.cpp'),
    Glob('./cmd/*.cpp')
]

env.Program('teal', src_files) 
